# Splitting with many Keys

In [2]:
import pandas as pd

In [4]:
dataset= pd.read_csv("Campus_Placement_Tracker_500.csv")

In [6]:
dataset.head()

,Roll Number,First Name,Last Name,Gender,Branch,Company,CTC (LPA),Job Role
0,22BCE6764,Shruti,Gupta,Female,Civil,Capgemini,3.43,Software Engineer
1,22BCE1856,Dev,Sharma,Male,Mechanical,Cognizant,5.63,Data Analyst
2,22BCE7769,Dev,Pandey,Male,ECE,TCS,4.17,Software Engineer
3,22BCE3591,Atharv,Mehta,Female,ECE,Infosys,3.42,DevOps Engineer
4,22BCE2533,Sai,Agarwal,Male,Civil,TCS,3.14,DevOps Engineer

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Roll Number  500 non-null    object
 1   First Name   500 non-null    object
 2   Last Name    500 non-null    object
 3   Gender       500 non-null    object
 4   Branch       500 non-null    object
 5   Company      500 non-null    object
 6   CTC (LPA)    500 non-null    float64
 7   Job Role     500 non-null    object
dtypes: float64(1), object(7)
memory usage: 31.4+ KB

In [10]:
dataset.Branch.nunique()

6

In [12]:
split1=dataset.groupby("Branch")

In [14]:
l= list(split1)
l

[('CSE',
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  5     22BCE5451     Saanvi    Pandey  Female    CSE     Amazon       5.92
  13    22BCE8918     Shruti      Iyer    Male    CSE    Infosys       4.90
  14    22BCE3599       Avni     Yadav  Female    CSE    Infosys       5.73
  18    22BCE6285      Kunal     Patel    Male    CSE  Microsoft       5.32
  22    22BCE4245       Avni       Das  Female    CSE     Amazon       4.72
  ..          ...        ...       ...     ...    ...        ...        ...
  473   22BCE6558      Meera     Ghosh    Male    CSE        TCS      11.53
  477   22BCE4231       Avni     Ghosh  Female    CSE      Wipro      24.08
  478   22BCE8618      Arjun     Ghosh  Female    CSE  Cognizant      26.30
  483   22BCE7695      Meera     Kumar  Female    CSE    Infosys      27.14
  485   22BCE2789      Kiara      Iyer  Female    CSE  Cognizant      12.07

                Job Role
  5    Software Engineer
  13      System Analyst
  14       Web Developer
  18      System Analyst
  22       Web Developer
  ..                 ...
  473     System Analyst
  477  Backend Developer
  478     System Analyst
  483      Web Developer
  485    DevOps Engineer

  [97 rows x 8 columns]),
 ('Civil',
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  0     22BCE6764     Shruti     Gupta  Female  Civil  Capgemini       3.43
  4     22BCE2533        Sai   Agarwal    Male  Civil        TCS       3.14
  9     22BCE4193      Kiara     Kumar    Male  Civil    Infosys       5.31
  19    22BCE2472      Tanya    Kapoor    Male  Civil        TCS       5.31
  23    22BCE9711       Yash     Mehta    Male  Civil  Microsoft       4.32
  ..          ...        ...       ...     ...    ...        ...        ...
  487   22BCE6374      Naman     Verma  Female  Civil        TCS      12.98
  490   22BCE2689      Laksh     Ghosh    Male  Civil    Infosys      17.99
  494   22BCE2099       Riya    Pandey  Female  Civil        TCS      14.67
  496   22BCE3684        Dev     Joshi  Female  Civil      Wipro      13.19
  497   22BCE3357     Ishaan     Reddy  Female  Civil     Google      12.04

                Job Role
  0    Software Engineer
  4      DevOps Engineer
  9    Software Engineer
  19      System Analyst
  23      System Analyst
  ..                 ...
  487       Data Analyst
  490      Web Developer
  494  Software Engineer
  496       Data Analyst
  497    DevOps Engineer

  [96 rows x 8 columns]),
 ('ECE',
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  2     22BCE7769        Dev    Pandey    Male    ECE        TCS       4.17
  3     22BCE3591     Atharv     Mehta  Female    ECE    Infosys       3.42
  11    22BCE3475       Sara     Reddy    Male    ECE  Capgemini       5.73
  15    22BCE9460      Naman     Reddy    Male    ECE  Cognizant       4.07
  29    22BCE4954      Kunal       Das    Male    ECE        TCS       4.04
  ..          ...        ...       ...     ...    ...        ...        ...
  470   22BCE3464       Avni     Singh    Male    ECE     Google      23.65
  479   22BCE7045    Kritika     Kumar    Male    ECE      Wipro      27.09
  482   22BCE3488       Riya       Das  Female    ECE  Cognizant      18.03
  484   22BCE5371     Aditya     Kumar  Female    ECE  Capgemini      20.23
  491   22BCE8865     Trisha       Das    Male    ECE     Amazon      20.34

                Job Role
  2    Software Engineer
  3      DevOps Engineer
  11     DevOps Engineer
  15        Data Analyst
  29     DevOps Engineer
  ..                 ...
  470    DevOps Engineer
  479       Data Analyst
  482      Web Developer
  484      Web Developer
  491     System Analyst

  [67 rows x 8 columns]),
 ('EEE',
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  20    22BCE9668       Avni     Reddy  Female    EEE  Cognizant       5.80
  21    22BCE4369      Kiara     Mehta  Female    EEE     Amazon       5.07
  26    22BCE5400       Sara    Pandey  Female    EEE        TCS       3.96
  39    22BCE8900       Yash     Reddy    Male    EEE    Infosys       3.10
  41    22BCE8224    Reyansh       Das  Female    EEE        TCS       3.98
  ..          ...        ...       ...     ...    ...        ...        ...
  458   22BCE5806    Kritika     Reddy  Female    EEE        TCS      10.76
  461   22BCE9670       Avni     Patel    Male    EEE  Capgemini      10.50
  464   22BCE5626    Krishna      Iyer    Male    EEE    Infosys      14.44
  476   22BCE1876       Sara      Iyer    Male    EEE     Google      17.91
  495   22BCE9836      Aarav     Verma    Male    EEE     Google      21.62

                Job Role
  20        Data Analyst
  21       Web Developer
  26       Web Developer
  39      System Analyst
  41     DevOps Engineer
  ..                 ...
  458  Backend Developer
  461  Software Engineer
  464       Data Analyst
  476  Backend Developer
  495  Backend Developer

  [82 rows x 8 columns]),
 ('IT',
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  6     22BCE2600      Aryan     Reddy  Female     IT  Cognizant       4.41
  12    22BCE5592      Aarav     Kumar  Female     IT  Capgemini       5.21
  16    22BCE3608      Aarav     Patel  Female     IT  Cognizant       4.66
  32    22BCE5587       Avni     Ghosh    Male     IT  Microsoft       5.60
  36    22BCE9016        Dev       Das  Female     IT     Google       3.94
  ..          ...        ...       ...     ...    ...        ...        ...
  486   22BCE9847      Naman     Singh    Male     IT  Capgemini      18.82
  488   22BCE1379      Anika    Mishra  Female     IT        TCS      23.29
  489   22BCE3750      Kiara     Sinha  Female     IT     Google       6.85
  492   22BCE8218        Dev      Nair    Male     IT      Wipro       8.13
  498   22BCE6715    Kritika    Kapoor    Male     IT        TCS      20.80

                Job Role
  6    Backend Developer
  12   Backend Developer
  16        Data Analyst
  32     DevOps Engineer
  36        Data Analyst
  ..                 ...
  486  Backend Developer
  488    DevOps Engineer
  489  Software Engineer
  492      Web Developer
  498     System Analyst

  [87 rows x 8 columns]),
 ('Mechanical',
      Roll Number First Name Last Name  Gender      Branch    Company  \
  1     22BCE1856        Dev    Sharma    Male  Mechanical  Cognizant
  7     22BCE3414      Harsh     Singh  Female  Mechanical    Infosys
  8     22BCE9616     Ananya    Kapoor    Male  Mechanical  Microsoft
  10    22BCE1711     Vihaan    Chopra    Male  Mechanical    Infosys
  17    22BCE7696      Aryan   Agarwal  Female  Mechanical  Cognizant
  ..          ...        ...       ...     ...         ...        ...
  443   22BCE6196        Dev    Sharma  Female  Mechanical  Capgemini
  472   22BCE5484     Atharv     Verma  Female  Mechanical      Wipro
  474   22BCE1282        Ira     Ghosh    Male  Mechanical  Cognizant
  493   22BCE7871    Krishna       Das    Male  Mechanical  Cognizant
  499   22BCE7062      Arjun    Kapoor    Male  Mechanical     Google

       CTC (LPA)           Job Role
  1         5.63       Data Analyst
  7         4.71    DevOps Engineer
  8         4.93  Software Engineer
  10        3.13    DevOps Engineer
  17        3.00  Backend Developer
  ..         ...                ...
  443      27.37     System Analyst
  472      26.62  Backend Developer
  474       8.38    DevOps Engineer
  493      21.34      Web Developer
  499      22.68     System Analyst

  [71 rows x 8 columns])]

In [16]:
len(l)

6

In [24]:
l[5][1]

,Roll Number,First Name,Last Name,Gender,Branch,Company,CTC (LPA),Job Role
1,22BCE1856,Dev,Sharma,Male,Mechanical,Cognizant,5.63,Data Analyst
7,22BCE3414,Harsh,Singh,Female,Mechanical,Infosys,4.71,DevOps Engineer
8,22BCE9616,Ananya,Kapoor,Male,Mechanical,Microsoft,4.93,Software Engineer
10,22BCE1711,Vihaan,Chopra,Male,Mechanical,Infosys,3.13,DevOps Engineer
17,22BCE7696,Aryan,Agarwal,Female,Mechanical,Cognizant,3.00,Backend Developer
...,...,...,...,...,...,...,...,...
443,22BCE6196,Dev,Sharma,Female,Mechanical,Capgemini,27.37,System Analyst
472,22BCE5484,Atharv,Verma,Female,Mechanical,Wipro,26.62,Backend Developer
474,22BCE1282,Ira,Ghosh,Male,Mechanical,Cognizant,8.38,DevOps Engineer
493,22BCE7871,Krishna,Das,Male,Mechanical,Cognizant,21.34,Web Developer
499,22BCE7062,Arjun,Kapoor,Male,Mechanical,Google,22.68,System Analyst

In [26]:
split2 = dataset.groupby(by=["Branch","Gender"])

In [28]:
l2=list(split2)
l2

[(('CSE', 'Female'),
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  5     22BCE5451     Saanvi    Pandey  Female    CSE     Amazon       5.92
  14    22BCE3599       Avni     Yadav  Female    CSE    Infosys       5.73
  22    22BCE4245       Avni       Das  Female    CSE     Amazon       4.72
  44    22BCE7173      Kiara   Agarwal  Female    CSE     Amazon       3.03
  50    22BCE2251      Tanya     Singh  Female    CSE  Microsoft       4.43
  53    22BCE8089     Ananya    Sharma  Female    CSE  Cognizant       4.45
  59    22BCE7198      Arjun     Joshi  Female    CSE  Microsoft       4.40
  74    22BCE2995     Aditya     Sinha  Female    CSE     Google       4.80
  81    22BCE3668       Pihu     Kumar  Female    CSE      Wipro       5.01
  95    22BCE1102     Ananya      Iyer  Female    CSE        TCS       5.82
  112   22BCE3477     Ishaan    Mishra  Female    CSE  Microsoft       3.40
  129   22BCE6537   Niharika      Nair  Female    CSE      Wipro       5.22
  138   22BCE6695      Kiara     Reddy  Female    CSE  Microsoft       4.57
  148   22BCE8814      Tanya     Kumar  Female    CSE     Amazon       5.45
  158   22BCE2116     Atharv     Singh  Female    CSE        TCS       4.05
  159   22BCE6827       Yash   Agarwal  Female    CSE        TCS       4.65
  161   22BCE3707     Atharv     Mehta  Female    CSE  Microsoft       5.49
  174   22BCE2849     Shruti     Kumar  Female    CSE      Wipro       4.64
  176   22BCE4196       Sara     Kumar  Female    CSE  Cognizant       4.11
  180   22BCE4676      Meera     Verma  Female    CSE     Google       3.70
  189   22BCE3189        Sai    Pandey  Female    CSE     Amazon       5.28
  193   22BCE3445       Sara     Kumar  Female    CSE  Capgemini       3.43
  205   22BCE2866       Riya    Chopra  Female    CSE    Infosys       3.45
  219   22BCE4758        Dev    Chopra  Female    CSE  Microsoft       5.33
  225   22BCE6500      Aryan     Patel  Female    CSE     Amazon       3.31
  226   22BCE6321   Niharika     Yadav  Female    CSE  Cognizant       5.87
  238   22BCE2798      Kabir    Sharma  Female    CSE  Microsoft       5.98
  239   22BCE1293       Yash     Sinha  Female    CSE  Microsoft       4.13
  263   22BCE9875     Ananya    Sharma  Female    CSE     Google      26.70
  264   22BCE2204       Riya     Sinha  Female    CSE        TCS      20.46
  269   22BCE7938      Naman    Chopra  Female    CSE  Capgemini      16.15
  283   22BCE6616    Reyansh     Kumar  Female    CSE        TCS      10.03
  292   22BCE3376     Aditya     Joshi  Female    CSE     Amazon      11.63
  305   22BCE5054    Krishna     Gupta  Female    CSE     Amazon       6.37
  306   22BCE7715     Prisha    Chopra  Female    CSE     Amazon      13.54
  315   22BCE4289     Trisha     Verma  Female    CSE  Capgemini      18.95
  317   22BCE9664       Avni      Iyer  Female    CSE      Wipro       8.93
  347   22BCE2971     Ananya     Sinha  Female    CSE     Google      17.86
  353   22BCE4536     Aditya   Agarwal  Female    CSE     Amazon      20.37
  365   22BCE9316       Yash   Agarwal  Female    CSE     Google       8.30
  374   22BCE5069      Laksh     Singh  Female    CSE  Cognizant      20.42
  378   22BCE1015      Arjun    Pandey  Female    CSE     Amazon      19.86
  385   22BCE9206     Aadhya     Gupta  Female    CSE  Capgemini       9.54
  386   22BCE1136    Reyansh      Nair  Female    CSE  Capgemini      12.71
  388   22BCE7673      Aarav       Das  Female    CSE  Capgemini      15.77
  413   22BCE1072         Om     Yadav  Female    CSE  Capgemini       6.85
  420   22BCE5134      Meera      Iyer  Female    CSE      Wipro      15.36
  428   22BCE4740     Atharv     Mehta  Female    CSE        TCS      16.21
  449   22BCE8773      Harsh    Pandey  Female    CSE  Cognizant      27.18
  451   22BCE4175       Sara     Ghosh  Female    CSE  Microsoft      19.02
  452   22BCE1931       Myra     Patel  Female    CSE  Capgemini      21.87
  460   22BCE8910    Kritika   Agarwal  Female    CSE        TCS      16.22
  471   22BCE4688     Vivaan     Patel  Female    CSE  Cognizant      19.93
  477   22BCE4231       Avni     Ghosh  Female    CSE      Wipro      24.08
  478   22BCE8618      Arjun     Ghosh  Female    CSE  Cognizant      26.30
  483   22BCE7695      Meera     Kumar  Female    CSE    Infosys      27.14
  485   22BCE2789      Kiara      Iyer  Female    CSE  Cognizant      12.07

                Job Role
  5    Software Engineer
  14       Web Developer
  22       Web Developer
  44     DevOps Engineer
  50        Data Analyst
  53        Data Analyst
  59     DevOps Engineer
  74       Web Developer
  81      System Analyst
  95     DevOps Engineer
  112     System Analyst
  129    DevOps Engineer
  138    DevOps Engineer
  148  Backend Developer
  158     System Analyst
  159      Web Developer
  161  Software Engineer
  174     System Analyst
  176       Data Analyst
  180      Web Developer
  189  Backend Developer
  193    DevOps Engineer
  205      Web Developer
  219      Web Developer
  225  Software Engineer
  226  Software Engineer
  238     System Analyst
  239      Web Developer
  263  Software Engineer
  264      Web Developer
  269       Data Analyst
  283      Web Developer
  292    DevOps Engineer
  305  Backend Developer
  306  Backend Developer
  315  Software Engineer
  317     System Analyst
  347  Software Engineer
  353  Software Engineer
  365      Web Developer
  374  Backend Developer
  378    DevOps Engineer
  385       Data Analyst
  386     System Analyst
  388       Data Analyst
  413  Backend Developer
  420     System Analyst
  428      Web Developer
  449     System Analyst
  451      Web Developer
  452     System Analyst
  460  Backend Developer
  471  Backend Developer
  477  Backend Developer
  478     System Analyst
  483      Web Developer
  485    DevOps Engineer  ),
 (('CSE', 'Male'),
      Roll Number First Name Last Name Gender Branch    Company  CTC (LPA)  \
  13    22BCE8918     Shruti      Iyer   Male    CSE    Infosys       4.90
  18    22BCE6285      Kunal     Patel   Male    CSE  Microsoft       5.32
  24    22BCE7667     Prisha    Mishra   Male    CSE  Microsoft       4.16
  27    22BCE8770       Pihu     Verma   Male    CSE      Wipro       4.50
  33    22BCE2387    Reyansh     Patel   Male    CSE  Cognizant       3.96
  63    22BCE7332     Ananya     Ghosh   Male    CSE        TCS       5.95
  82    22BCE1377       Yash     Gupta   Male    CSE  Cognizant       4.13
  87    22BCE6423      Kabir     Reddy   Male    CSE  Microsoft       5.88
  93    22BCE5141       Avni     Kumar   Male    CSE    Infosys       5.79
  99    22BCE1806     Ishaan    Chopra   Male    CSE  Cognizant       3.54
  118   22BCE5247      Kabir      Iyer   Male    CSE        TCS       4.58
  125   22BCE1445       Riya   Agarwal   Male    CSE  Microsoft       4.32
  130   22BCE9230     Saanvi       Das   Male    CSE    Infosys       3.05
  142   22BCE2981       Yash    Sharma   Male    CSE  Capgemini       5.17
  149   22BCE8546      Tanvi     Verma   Male    CSE  Capgemini       4.84
  164   22BCE3360      Meera     Sinha   Male    CSE    Infosys       4.27
  173   22BCE1576        Dev    Mishra   Male    CSE  Microsoft       4.50
  177   22BCE5654      Arjun     Patel   Male    CSE        TCS       3.21
  181   22BCE9368         Om     Patel   Male    CSE  Capgemini       4.56
  185   22BCE6086    Reyansh     Mehta   Male    CSE        TCS       3.98
  188   22BCE1954     Saanvi     Kumar   Male    CSE  Microsoft       5.70
  221   22BCE7246       Sara    Mishra   Male    CSE  Capgemini       5.21
  274   22BCE9470      Kabir      Iyer   Male    CSE     Amazon      19.66
  278   22BCE9862       Pihu      Nair   Male    CSE      Wipro      26.34
  304   22BCE1237       Myra    Sharma   Male    CSE     Amazon      19.21
  313   22BCE5924      Rohan       Das   Male    CSE  Capgemini      28.17
  328   22BCE3114    Reyansh     Yadav   Male    CSE  Cognizant      11.76
  336   22BCE3571     Vivaan    Chopra   Male    CSE      Wipro      29.53
  352   22BCE8675      Meera     Ghosh   Male    CSE  Capgemini      22.30
  364   22BCE8821        Sai     Mehta   Male    CSE     Google      23.11
  380   22BCE6405     Vivaan    Sharma   Male    CSE      Wipro      24.82
  390   22BCE5212       Diya   Agarwal   Male    CSE      Wipro      13.75
  409   22BCE8050        Ira    Chopra   Male    CSE     Google      15.44
  421   22BCE9766   Niharika   Agarwal   Male    CSE  Cognizant       7.02
  422   22BCE1871       Riya     Verma   Male    CSE  Cognizant      17.65
  435   22BCE3247       Avni     Mehta   Male    CSE  Microsoft      26.36
  436   22BCE4321     Vihaan     Verma   Male    CSE  Cognizant      24.98
  447   22BCE1161      Tanya    Chopra   Male    CSE     Amazon      28.88
  459   22BCE1074     Ananya    Chopra   Male    CSE     Amazon       6.60
  473   22BCE6558      Meera     Ghosh   Male    CSE        TCS      11.53

                Job Role
  13      System Analyst
  18      System Analyst
  24        Data Analyst
  27   Software Engineer
  33      System Analyst
  63     DevOps Engineer
  82     DevOps Engineer
  87        Data Analyst
  93   Software Engineer
  99        Data Analyst
  118  Software Engineer
  125  Backend Developer
  130       Data Analyst
  142       Data Analyst
  149  Software Engineer
  164  Software Engineer
  173    DevOps Engineer
  177      Web Developer
  181      Web Developer
  185     System Analyst
  188    DevOps Engineer
  221  Software Engineer
  274       Data Analyst
  278  Software Engineer
  304    DevOps Engineer
  313  Software Engineer
  328    DevOps Engineer
  336      Web Developer
  352       Data Analyst
  364      Web Developer
  380  Software Engineer
  390      Web Developer
  409      Web Developer
  421  Software Engineer
  422      Web Developer
  435  Backend Developer
  436       Data Analyst
  447  Backend Developer
  459  Backend Developer
  473     System Analyst  ),
 (('Civil', 'Female'),
      Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
  0     22BCE6764     Shruti     Gupta  Female  Civil  Capgemini       3.43
  48    22BCE5935      Anika    Mishra  Female  Civil     Amazon       3.60
  61    22BCE5607        Dev      Iyer  Female  Civil      Wipro       5.07
  68    22BCE8106     Shruti    Pandey  Female  Civil      Wipro       3.68
  72    22BCE3461      Laksh     Yadav  Female  Civil     Amazon       4.31
  79    22BCE5707     Shruti     Reddy  Female  Civil        TCS       5.87
  83    22BCE2272      Aarav    Kapoor  Female  Civil     Amazon       4.59
  90    22BCE3131      Kiara     Singh  Female  Civil      Wipro       3.28
  106   22BCE9769      Laksh       Das  Female  Civil  Cognizant       5.17
  131   22BCE2219     Ananya     Mehta  Female  Civil  Microsoft       3.55
  147   22BCE7900    Reyansh    Chopra  Female  Civil  Microsoft       3.99
  162   22BCE1437       Avni      Nair  Female  Civil     Amazon       3.70
  186   22BCE8621     Vihaan    Pandey  Female  Civil  Cognizant       3.50
  194   22BCE1105       Pihu    Mishra  Female  Civil     Google       5.71
  237   22BCE3169     Aditya    Pandey  Female  Civil        TCS       3.37
  246   22BCE1976      Laksh     Joshi  Female  Civil  Microsoft       3.34
  258   22BCE4951     Atharv     Verma  Female  Civil  Microsoft      15.32
  259   22BCE8903     Ananya     Verma  Female  Civil      Wipro      21.80
  273   22BCE9867      Kabir      Nair  Female  Civil        TCS      12.49
  282   22BCE6537     Trisha     Kumar  Female  Civil        TCS      27.72
  300   22BCE8931      Kabir     Joshi  Female  Civil  Capgemini      21.27
  311   22BCE6184       Yash     Ghosh  Female  Civil        TCS      22.81
  322   22BCE9648      Aarav     Mehta  Female  Civil     Google      16.28
  327   22BCE7915        Sai     Reddy  Female  Civil     Amazon      12.55
  331   22BCE7423    Reyansh   Agarwal  Female  Civil     Amazon      23.65
  332   22BCE6174       Sara     Kumar  Female  Civil     Google      25.19
  341   22BCE1337      Anika     Kumar  Female  Civil     Amazon      23.56
  360   22BCE7695     Vihaan     Gupta  Female  Civil    Infosys       7.77
  368   22BCE6790        Ira     Verma  Female  Civil        TCS       9.51
  369   22BCE9658     Trisha     Sinha  Female  Civil     Amazon      20.65
  373   22BCE1428    Krishna     Gupta  Female  Civil  Capgemini      29.34
  403   22BCE7568     Aditya     Ghosh  Female  Civil     Amazon      20.44
  406   22BCE8151     Saanvi     Gupta  Female  Civil  Capgemini       9.37
  414   22BCE5640     Ananya      Nair  Female  Civil  Cognizant       6.75
  425   22BCE3118      Aarav     Joshi  Female  Civil  Microsoft      27.12
  444   22BCE8376     Trisha     Sinha  Female  Civil  Capgemini      27.09
  462   22BCE3192      Tanya    Pandey  Female  Civil     Google      19.17
  466   22BCE3654     Trisha    Kapoor  Female  Civil     Amazon      29.03
  480   22BCE4377       Myra     Mehta  Female  Civil  Cognizant      16.65
  487   22BCE6374      Naman     Verma  Female  Civil        TCS      12.98
  494   22BCE2099       Riya    Pandey  Female  Civil        TCS      14.67
  496   22BCE3684        Dev     Joshi  Female  Civil      Wipro      13.19
  497   22BCE3357     Ishaan     Reddy  Female  Civil     Google      12.04

                Job Role
  0    Software Engineer
  48   Software Engineer
  61   Backend Developer
  68      System Analyst
  72   Backend Developer
  79      System Analyst
  83     DevOps Engineer
  90     DevOps Engineer
  106  Software Engineer
  131       Data Analyst
  147  Backend Developer
  162       Data Analyst
  186    DevOps Engineer
  194      Web Developer
  237  Backend Developer
  246       Data Analyst
  258  Backend Developer
  259    DevOps Engineer
  273    DevOps Engineer
  282      Web Developer
  300  Software Engineer
  311     System Analyst
  322     System Analyst
  327    DevOps Engineer
  331  Software Engineer
  332     System Analyst
  341  Backend Developer
  360  Software Engineer
  368  Backend Developer
  369    DevOps Engineer
  373     System Analyst
  403  Backend Developer
  406  Software Engineer
  414     System Analyst
  425  Software Engineer
  444  Backend Developer
  462  Backend Developer
  466      Web Developer
  480    DevOps Engineer
  487       Data Analyst
  494  Software Engineer
  496       Data Analyst
  497    DevOps Engineer  ),
 (('Civil', 'Male'),
      Roll Number First Name Last Name Gender Branch    Company  CTC (LPA)  \
  4     22BCE2533        Sai   Agarwal   Male  Civil        TCS       3.14
  9     22BCE4193      Kiara     Kumar   Male  Civil    Infosys       5.31
  19    22BCE2472      Tanya    Kapoor   Male  Civil        TCS       5.31
  23    22BCE9711       Yash     Mehta   Male  Civil  Microsoft       4.32
  25    22BCE5645        Sai    Pandey   Male  Civil  Microsoft       4.28
  30    22BCE7501     Shruti    Kapoor   Male  Civil  Microsoft       4.73
  35    22BCE3910     Saanvi     Sinha   Male  Civil        TCS       3.98
  60    22BCE4553      Kabir     Joshi   Male  Civil    Infosys       4.96
  69    22BCE5986      Aryan     Mehta   Male  Civil  Cognizant       4.43
  71    22BCE8954       Sara    Chopra   Male  Civil     Google       4.71
  75    22BCE4450     Prisha     Mehta   Male  Civil    Infosys       5.69
  86    22BCE7551     Aadhya     Yadav   Male  Civil  Capgemini       4.61
  115   22BCE4948      Kabir      Nair   Male  Civil     Google       3.15
  116   22BCE8492     Atharv   Agarwal   Male  Civil     Amazon       3.07
  119   22BCE5619     Vivaan    Chopra   Male  Civil     Amazon       5.12
  120   22BCE3250       Sara     Joshi   Male  Civil  Microsoft       5.16
  121   22BCE9792      Laksh     Yadav   Male  Civil  Cognizant       5.92
  123   22BCE8105    Reyansh     Reddy   Male  Civil    Infosys       3.89
  132   22BCE3113      Naman    Chopra   Male  Civil     Amazon       3.58
  166   22BCE8296      Arjun     Singh   Male  Civil  Capgemini       5.04
  183   22BCE6207       Riya     Mehta   Male  Civil  Capgemini       5.19
  191   22BCE4272   Niharika     Singh   Male  Civil  Capgemini       4.53
  198   22BCE2228      Naman     Joshi   Male  Civil        TCS       3.21
  201   22BCE1155      Naman      Iyer   Male  Civil        TCS       5.39
  206   22BCE3336      Tanya      Iyer   Male  Civil  Cognizant       5.86
  209   22BCE3392     Vivaan     Verma   Male  Civil     Amazon       3.46
  212   22BCE9866      Tanya      Nair   Male  Civil        TCS       3.87
  228   22BCE6101     Aadhya     Joshi   Male  Civil        TCS       3.88
  229   22BCE4348      Naman     Gupta   Male  Civil  Microsoft       3.99
  235   22BCE5496      Harsh    Pandey   Male  Civil  Capgemini       5.42
  244   22BCE2469      Anika     Kumar   Male  Civil     Amazon       5.16
  256   22BCE5335    Krishna      Nair   Male  Civil      Wipro      16.95
  275   22BCE7170    Kritika    Chopra   Male  Civil        TCS      29.67
  288   22BCE4564      Arjun     Reddy   Male  Civil    Infosys      22.44
  291   22BCE8608      Kiara     Mehta   Male  Civil  Capgemini      11.46
  324   22BCE4123      Tanvi   Agarwal   Male  Civil  Capgemini      23.00
  329   22BCE3874       Pihu    Mishra   Male  Civil  Capgemini      13.18
  335   22BCE8916     Saanvi     Yadav   Male  Civil     Google      20.40
  348   22BCE2933      Aarav    Sharma   Male  Civil  Cognizant      10.43
  351   22BCE1397       Yash     Patel   Male  Civil  Microsoft      26.19
  362   22BCE7419        Dev    Chopra   Male  Civil        TCS      16.24
  402   22BCE4382       Diya     Kumar   Male  Civil     Google      29.38
  408   22BCE5042      Arjun    Sharma   Male  Civil  Capgemini       6.08
  430   22BCE8736     Atharv      Nair   Male  Civil    Infosys      21.87
  433   22BCE2370      Laksh     Joshi   Male  Civil  Microsoft      20.35
  439   22BCE4861      Kabir     Verma   Male  Civil    Infosys      15.73
  445   22BCE1131      Aarav     Yadav   Male  Civil  Microsoft       8.70
  453   22BCE8951      Aryan     Sinha   Male  Civil  Capgemini      23.12
  454   22BCE3945      Rohan     Verma   Male  Civil        TCS      11.38
  456   22BCE7413     Prisha     Joshi   Male  Civil     Google      21.45
  463   22BCE5650      Arjun    Kapoor   Male  Civil     Amazon      10.33
  467   22BCE3260       Sara      Nair   Male  Civil        TCS       6.00
  490   22BCE2689      Laksh     Ghosh   Male  Civil    Infosys      17.99

                Job Role
  4      DevOps Engineer
  9    Software Engineer
  19      System Analyst
  23      System Analyst
  25     DevOps Engineer
  30       Web Developer
  35   Backend Developer
  60   Backend Developer
  69      System Analyst
  71   Software Engineer
  75       Web Developer
  86   Backend Developer
  115  Software Engineer
  116     System Analyst
  119  Software Engineer
  120      Web Developer
  121  Backend Developer
  123       Data Analyst
  132      Web Developer
  166       Data Analyst
  183  Backend Developer
  191  Backend Developer
  198  Backend Developer
  201      Web Developer
  206  Backend Developer
  209      Web Developer
  212  Backend Developer
  228  Backend Developer
  229  Backend Developer
  235     System Analyst
  244       Data Analyst
  256    DevOps Engineer
  275    DevOps Engineer
  288       Data Analyst
  291       Data Analyst
  324    DevOps Engineer
  329  Backend Developer
  335  Backend Developer
  348  Backend Developer
  351      Web Developer
  362  Backend Developer
  402       Data Analyst
  408     System Analyst
  430  Software Engineer
  433     System Analyst
  439      Web Developer
  445  Backend Developer
  453     System Analyst
  454  Software Engineer
  456     System Analyst
  463       Data Analyst
  467    DevOps Engineer
  490      Web Developer  ),
 (('ECE', 'Female'),

In [30]:
len(l2)

12

In [40]:
l2[4]

(('ECE', 'Female'),
     Roll Number First Name Last Name  Gender Branch    Company  CTC (LPA)  \
 3     22BCE3591     Atharv     Mehta  Female    ECE    Infosys       3.42
 40    22BCE2161      Kabir    Pandey  Female    ECE     Amazon       3.65
 45    22BCE2435     Saanvi     Gupta  Female    ECE    Infosys       3.48
 51    22BCE2083      Anika     Patel  Female    ECE     Amazon       5.87
 73    22BCE1906       Avni    Pandey  Female    ECE  Cognizant       5.22
 85    22BCE1212     Shruti    Mishra  Female    ECE  Microsoft       4.35
 97    22BCE5784     Vihaan     Sinha  Female    ECE        TCS       4.95
 151   22BCE5432    Krishna     Reddy  Female    ECE     Google       4.66
 157   22BCE8957      Kabir     Singh  Female    ECE  Capgemini       4.95
 171   22BCE7552   Niharika    Kapoor  Female    ECE  Cognizant       3.98
 182   22BCE9161     Trisha     Joshi  Female    ECE  Capgemini       3.66
 222   22BCE1806      Anika      Iyer  Female    ECE      Wipro       5.84
 230   22BCE4082         Om     Mehta  Female    ECE  Capgemini       3.35
 236   22BCE4680      Laksh     Ghosh  Female    ECE        TCS       4.36
 249   22BCE9079       Yash     Reddy  Female    ECE     Amazon       4.50
 254   22BCE1726       Riya     Reddy  Female    ECE    Infosys      24.14
 272   22BCE7844     Shruti    Chopra  Female    ECE  Capgemini      10.98
 295   22BCE6370        Sai     Patel  Female    ECE  Microsoft       9.02
 303   22BCE6925      Meera    Pandey  Female    ECE     Google      25.16
 325   22BCE8383      Meera    Chopra  Female    ECE     Google      29.91
 334   22BCE1848        Dev     Patel  Female    ECE    Infosys      27.52
 338   22BCE3545      Meera     Patel  Female    ECE  Microsoft      26.68
 344   22BCE5869     Vihaan     Reddy  Female    ECE     Google      11.24
 358   22BCE4087      Aarav     Kumar  Female    ECE    Infosys       8.51
 366   22BCE8482     Aadhya    Kapoor  Female    ECE      Wipro      15.74
 367   22BCE4456     Prisha     Kumar  Female    ECE  Cognizant      16.03
 398   22BCE5093      Tanvi     Yadav  Female    ECE    Infosys      22.52
 417   22BCE6639     Shruti    Sharma  Female    ECE        TCS      28.17
 482   22BCE3488       Riya       Das  Female    ECE  Cognizant      18.03
 484   22BCE5371     Aditya     Kumar  Female    ECE  Capgemini      20.23

               Job Role
 3      DevOps Engineer
 40      System Analyst
 45       Web Developer
 51   Software Engineer
 73       Web Developer
 85      System Analyst
 97   Software Engineer
 151  Backend Developer
 157     System Analyst
 171       Data Analyst
 182  Backend Developer
 222      Web Developer
 230  Backend Developer
 236    DevOps Engineer
 249  Software Engineer
 254     System Analyst
 272     System Analyst
 295  Backend Developer
 303  Software Engineer
 325      Web Developer
 334       Data Analyst
 338     System Analyst
 344  Backend Developer
 358       Data Analyst
 366  Backend Developer
 367    DevOps Engineer
 398    DevOps Engineer
 417    DevOps Engineer
 482      Web Developer
 484      Web Developer  )

In [42]:
l2[4][0]

('ECE', 'Female')

In [44]:
l2[4][1]

,Roll Number,First Name,Last Name,Gender,Branch,Company,CTC (LPA),Job Role
3,22BCE3591,Atharv,Mehta,Female,ECE,Infosys,3.42,DevOps Engineer
40,22BCE2161,Kabir,Pandey,Female,ECE,Amazon,3.65,System Analyst
45,22BCE2435,Saanvi,Gupta,Female,ECE,Infosys,3.48,Web Developer
51,22BCE2083,Anika,Patel,Female,ECE,Amazon,5.87,Software Engineer
73,22BCE1906,Avni,Pandey,Female,ECE,Cognizant,5.22,Web Developer
85,22BCE1212,Shruti,Mishra,Female,ECE,Microsoft,4.35,System Analyst
97,22BCE5784,Vihaan,Sinha,Female,ECE,TCS,4.95,Software Engineer
151,22BCE5432,Krishna,Reddy,Female,ECE,Google,4.66,Backend Developer
157,22BCE8957,Kabir,Singh,Female,ECE,Capgemini,4.95,System Analyst
171,22BCE7552,Niharika,Kapoor,Female,ECE,Cognizant,3.98,Data Analyst
182,22BCE9161,Trisha,Joshi,Female,ECE,Capgemini,3.66,Backend Developer
222,22BCE1806,Anika,Iyer,Female,ECE,Wipro,5.84,Web Developer
230,22BCE4082,Om,Mehta,Female,ECE,Capgemini,3.35,Backend Developer
236,22BCE4680,Laksh,Ghosh,Female,ECE,TCS,4.36,DevOps Engineer
249,22BCE9079,Yash,Reddy,Female,ECE,Amazon,4.50,Software Engineer
254,22BCE1726,Riya,Reddy,Female,ECE,Infosys,24.14,System Analyst
272,22BCE7844,Shruti,Chopra,Female,ECE,Capgemini,10.98,System Analyst
295,22BCE6370,Sai,Patel,Female,ECE,Microsoft,9.02,Backend Developer
303,22BCE6925,Meera,Pandey,Female,ECE,Google,25.16,Software Engineer
325,22BCE8383,Meera,Chopra,Female,ECE,Google,29.91,Web Developer
334,22BCE1848,Dev,Patel,Female,ECE,Infosys,27.52,Data Analyst
338,22BCE3545,Meera,Patel,Female,ECE,Microsoft,26.68,System Analyst
344,22BCE5869,Vihaan,Reddy,Female,ECE,Google,11.24,Backend Developer
358,22BCE4087,Aarav,Kumar,Female,ECE,Infosys,8.51,Data Analyst
366,22BCE8482,Aadhya,Kapoor,Female,ECE,Wipro,15.74,Backend Developer
367,22BCE4456,Prisha,Kumar,Female,ECE,Cognizant,16.03,DevOps Engineer
398,22BCE5093,Tanvi,Yadav,Female,ECE,Infosys,22.52,DevOps Engineer
417,22BCE6639,Shruti,Sharma,Female,ECE,TCS,28.17,DevOps Engineer
482,22BCE3488,Riya,Das,Female,ECE,Cognizant,18.03,Web Developer
484,22BCE5371,Aditya,Kumar,Female,ECE,Capgemini,20.23,Web Developer

In [46]:
l2[4][2]

IndexError: tuple index out of range